### ISSUE TITLE
glide issue

### ISSUE THREAD

**Issue by neuberfran** [neuberfran/FirebaseArcCompB#2]
**images do not appear on the left side.**

Fetching data failed, class android.os.ParcelFileDescriptor, LOCAL Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed Cause (1 of 1): class java.io.FileNotFoundException: open failed: ENOENT (No such file or directory) 2019-07-09 21:16:45.357 27516-27516/app.sinanyilmaz.firebasearccomp W/Glide: Load failed for com.google.android.gms.tasks.zzu@ca88582 with size [270x270] class com.bumptech.glide.load.engine.GlideException: Failed to load resource

**images do not appear on the left side.**

![Screenshot_20190812-132937_FirebaseArcComp](https://user-images.githubusercontent.com/38701397/62883802-cf21a000-bce9-11e9-84ff-f61d858e82d0.jpg)

**references:**

https://github.com/SinanYilmaz9/FirebaseArcComp/issues/2

https://github.com/bumptech/glide/issues/3410

**Comment by neuberfran** [comment]
![captura_de_tela_2019-09-03_a__s_20 32 44](https://user-images.githubusercontent.com/38701397/64399555-2e4fa780-d03f-11e9-9dd0-f3600aa921ac.png)
![Captura de Tela 2019-08-29 às 18 00 16](https://user-images.githubusercontent.com/38701397/64399556-2ee83e00-d03f-11e9-8896-a273dbf682ec.png)

**Comment by neuberfran** [comment]
Solved:
fun uploadPicture(intentData: Intent) {

        val selectedUri = intentData.data
        val photoRef = FirebaseStorage.getInstance()
                .reference.child("photos")
                .child(selectedUri!!.lastPathSegment!!)

        val uploadTask = photoRef.putFile(selectedUri)
        uploadTask.continueWithTask(Continuation<UploadTask.TaskSnapshot, Task<Uri>> { task ->

            if (!task.isSuccessful) {
                task.exception?.let {
                    throw it
                }
            }
            return@Continuation photoRef.downloadUrl
        }).addOnCompleteListener { task ->
            if (task.isSuccessful) {
                val downloadUri = task.result
                photoUrl = downloadUri.toString()
                pictureUploadIsSuccessful.setValue(true)
            } else {
                // Handle failures
                pictureUploadIsSuccessful.setValue(false)
                // ...
            }
        }
    }

**Comment by AhmadAyyaz1993** [comment]
post method here where you are trying to load images?
